name: Build git

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git version tag to build'
        required: true
        type: string

env:
  branch_name: main

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    if: ${{ inputs.tag }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest }
          - { os: macos-latest }
          - { os: macos-13 }

    steps:
    - uses: actions/checkout@v4
      with:
        repository: git/git
        ref: ${{ inputs.tag }}

    - name: Setup linux dependencies
      if: matrix.config.os == 'ubuntu-latest'
      shell: bash -el {0}
      run: |
        sudo apt-get install -y dh-autoreconf libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev

    - name: Setup MacOS dependencies
      if: matrix.config.os != 'ubuntu-latest'
      run: |
        brew install automake expat curl make

    - name: Build webview packed (linux)
      shell: bash -el {0}
      run: |
        make configure
        RUNTIME_PREFIX=True ./configure --prefix=$(pwd)/build --with-curl
        make
        make install
        mkdir -p artifacts
        tar -czf artifacts/git-${{ inputs.tag }}-portable.tar.gz build
    - name: Update release assets and text
      uses: actions/github-script@v7
      env:
        SEARCH_PATTERN: "artifacts/*"
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const script = require('./.github/actions/update_unstable.js');
          const output = await script({github, context, glob});
          console.log(output);
